name: Phfosfrustudio
favicon: null
layout_spectrum: 0.11186437075957656
typography_spectrum: 0.9723163160961121
title: 'carry a torch  '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6952833253890276
  lightness: 0.20163190714083612
  saturation: 0.5736709155607969
  rhythmicContrast: 0.315362460212782
purpose: []
